### ISSUE TITLE
space and line feed

### ISSUE THREAD

**Issue by w307892309** [ko1nksm/sh-hmac-sha1#1]
incorrectly handles space (" ") and line feed ("\n") characters in the "value" field

**Comment by ko1nksm** [comment]
It seems to work fine to me.

```console
$ printf 'va lue' | openssl dgst -sha1 -hmac 'secret_key'
SHA1(stdin)= bb18fddc564072c2a11f4939a4c6a59cdf22ad99

$ printf 'va lue' | ./hmac-sha1 <(printf 'secret_key')
bb18fddc564072c2a11f4939a4c6a59cdf22ad99
```

```console
$ printf 'va\nlue' | openssl dgst -sha1 -hmac 'secret_key'
SHA1(stdin)= d694732f0c68f2ea58dedf1b2d67a460938ec732

$ printf 'va\nlue' | ./hmac-sha1 <(printf 'secret_key')
d694732f0c68f2ea58dedf1b2d67a460938ec732
```

**Comment by w307892309** [comment]
I apologize for disturbing you
I tried to collect everything in one file with my code and apparently I made a mistake somewhere
I think it's the difference between #!/bin/bash and #!/bin/sh ))) 
Thanks for the prompt response
